### ISSUE TITLE
Previous Fortnight pay has incorrect date in Hyperchicken

### ISSUE THREAD

**Issue by bchiha** [jonoxyz/lazypay#1]
Great stuff Jono!

I'm on a Mac and requested the previous fortnight's pay.  I entered the date "20240128".  The correct data was scraped from MetroGo and loaded correctly in Hyperchicken,  But the date range in Hyperchicken displays

<img width="367" alt="image" src="https://github.com/jonoxyz/lazypay/assets/1054943/13b7ee8d-43cb-4327-9a4c-1a6bf188e45b">

I've also noticed if I just press Enter to select the last pay period, it puts the date range in hyperchicken as the previous pay period too...

I've attached the terminal dump also:

`
The laziest way to check your pay
Version 1.0
Visit https://www.lazypay.xyz

The most recent fortnight was 2024-02-11
If you want to check your pay for the most recent fortnight press Enter
If you want to check a different fortnight
Enter the start date in the format YYYYMMDD
20240128
20240128
###########################################
Fortnight date 20240128 selected.
###########################################

Do you wish to calculate just one fortnights pay
or all fortnights since the specified date?

To calculate a single fortnight pay press Enter.
If you wish to all pays since specified date type Y.

Checking multiple pays: False
Fetching day 0
Fetching day 1
Fetching day 2
Fetching day 3
Fetching day 4
Fetching day 5
Fetching day 6
Fetching day 7
Fetching day 8
Fetching day 9
Fetching day 10
Fetching day 11
Fetching day 12
Fetching day 13

printing shift list
[{'paid': False, 'type': 'OFF'}, {'paid': True, 'type': 'running', 'sign_on': '1600', 'sign_off': '0000', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'running', 'sign_on': '1400', 'sign_off': '2200', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'sick', 'sign_on': '', 'sign_off': '', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'sick', 'sign_on': '', 'sign_off': '', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'sick', 'sign_on': '', 'sign_off': '', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'running', 'sign_on': '1045', 'sign_off': '1843', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'running', 'sign_on': '0820', 'sign_off': '1620', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'running', 'sign_on': '0934', 'sign_off': '1700', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'running', 'sign_on': '0630', 'sign_off': '1418', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'running', 'sign_on': '0952', 'sign_off': '1740', 'ojt': False, 'wasted_meal': False}, {'paid': True, 'type': 'running', 'sign_on': '0630', 'sign_off': '1418', 'ojt': False, 'wasted_meal': False}, {'paid': False, 'type': 'OFF'}, {'paid': True, 'type': 'running', 'sign_on': '0530', 'sign_off': '1320', 'ojt': False, 'wasted_meal': False}]
Entering Shift 0 : {'paid': False, 'type': 'OFF'}
Entering Shift 1 : {'paid': True, 'type': 'running', 'sign_on': '1600', 'sign_off': '0000', 'ojt': False, 'wasted_meal': False}
Entering Shift 2 : {'paid': True, 'type': 'running', 'sign_on': '1400', 'sign_off': '2200', 'ojt': False, 'wasted_meal': False}
Entering Shift 3 : {'paid': True, 'type': 'sick', 'sign_on': '', 'sign_off': '', 'ojt': False, 'wasted_meal': False}
Entering Shift 4 : {'paid': True, 'type': 'sick', 'sign_on': '', 'sign_off': '', 'ojt': False, 'wasted_meal': False}
Entering Shift 5 : {'paid': True, 'type': 'sick', 'sign_on': '', 'sign_off': '', 'ojt': False, 'wasted_meal': False}
Entering Shift 6 : {'paid': True, 'type': 'running', 'sign_on': '1045', 'sign_off': '1843', 'ojt': False, 'wasted_meal': False}
Entering Shift 7 : {'paid': True, 'type': 'running', 'sign_on': '0820', 'sign_off': '1620', 'ojt': False, 'wasted_meal': False}
Entering Shift 8 : {'paid': True, 'type': 'running', 'sign_on': '0934', 'sign_off': '1700', 'ojt': False, 'wasted_meal': False}
Entering Shift 9 : {'paid': True, 'type': 'running', 'sign_on': '0630', 'sign_off': '1418', 'ojt': False, 'wasted_meal': False}
Entering Shift 10 : {'paid': True, 'type': 'running', 'sign_on': '0952', 'sign_off': '1740', 'ojt': False, 'wasted_meal': False}
Entering Shift 11 : {'paid': True, 'type': 'running', 'sign_on': '0630', 'sign_off': '1418', 'ojt': False, 'wasted_meal': False}
Entering Shift 12 : {'paid': False, 'type': 'OFF'}
Entering Shift 13 : {'paid': True, 'type': 'running', 'sign_on': '0530', 'sign_off': '1320', 'ojt': False, 'wasted_meal': False}
`

**Comment by bchiha** [comment]
Looks like the offending code is here:

```
# Set correct fortnight in Hyperchicken
time.sleep(0.2)
driver.find_element(By.XPATH, "/html/body/div[2]/div[1]/div/div[3]/span[1]").click()
for i in range(fortnight_number):
    time.sleep(0.05)

    # Click back to navigate to the correct fortnight
    driver.find_element(By.XPATH, "/html/body/div[2]/div[1]/div/div[3]/span[1]").click()

```

Hyperchicken by default starts with the previous pay period.  The click() prior to the for loop sets it back to the previous fortnight.  As `fortnight_number` is 0, the for loop is skipped.  When I removed the first click() it seemed to fix the problem.  Havent tested for multiple pays, but should be fine it think!

**Comment by jonoxyz** [comment]
Thank you for pointing this out. You are totally correct. When I added the loop to check support previous fortnights I did not remove the initial click that was no longer needed. I have fixed this now. 

That being said the train notes HyperGo extension does this but better anyway. Perhaps in the future I will update this project to use the MetroGo API and simply import the data in to HyperChicken.
